name: portfolio_ls
description: "Una plataforma digital que exhibe mi trayectoria profesional y creativa con un enfoque visual y funcional."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

#
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.5
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  http: ^1.1.0
  path_provider: ^2.1.1
  universal_html: ^2.2.4
  printing: ^5.11.0
  pdf: ^3.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon16.png"
    background_color: "#1A1C1E"
    theme_color: "#1A1C1E"

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/
    - assets/icon/
    - assets/slide/
    - assets/cv_data.json
    - assets/appainter_theme.json
    - assets/appainter_theme_dark.json
    - assets/appainter_theme_blue.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Light.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 600
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: fonts/Poppins-Bold.ttf
          weight: 800
        - asset: fonts/Poppins-Bold.ttf
          weight: 900

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
